title:               Relatively Ignorant
description:         'A blog on things about which I may or may not know stuff'
paginate:            5

url:                 https://blog.michaelstrasser.com
permalink:           /:year/:month/:title/

exclude:
  - .gitignore
  - CNAME
  - README.md
include:
  - .well-known

author:
  name:              Michael Strasser
  email:             atom@michaelstrasser.com
  url:               http://michaelstrasser.com/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

version:             2.0

github:
  repo: https://github.com/mjstrasser/mjstrasser.github.io
